---
title: "Temporal variation in transmission during the COVID-19 outbreak - Brazil"
site: distill::distill_website
bibliography: library.bib
---


```{r}
title <- FALSE
```

This page was adapted from [EpiForecasts](https://epiforecasts.io/covid) to report COVID-19 estimates in Brazilian states and municipalities. You can find the original website in: https://epiforecasts.io/covid and the original source code in https://github.com/marcuswac/covid-br-epiforecasts

Reports available:
- [Brazil - states](https://marcuswac.github.io/covid-br-epiforecasts/posts/national/brazil/)

Municipalities of northeast Brazil states:
- [Alagoas](https://marcuswac.github.io/covid-rt-brazil-subregional/states/AL/)
- [Bahia](https://marcuswac.github.io/covid-rt-brazil-subregional/states/BA/)
- [Ceará](https://marcuswac.github.io/covid-rt-brazil-subregional/states/CE/)
- [Maranhão](https://marcuswac.github.io/covid-rt-brazil-subregional/states/MA/)
- [Paraíba](https://marcuswac.github.io/covid-rt-brazil-subregional/states/PB/)
- [Pernambuco](https://marcuswac.github.io/covid-rt-brazil-subregional/states/PE/)
- [Piauí](https://marcuswac.github.io/covid-rt-brazil-subregional/states/PI/)
- [Rio Grande do Norte](https://marcuswac.github.io/covid-rt-brazil-subregional/states/RN/)
- [Sergipe](https://marcuswac.github.io/covid-rt-brazil-subregional/states/SE/)


**More information** For more detail and the limitations of these estimates please see our [methods](https://epiforecasts.io/covid/methods.html)), our [preprint](https://wellcomeopenresearch.org/articles/5-112/v1)[@rtwebsite], the [documentation of our transmission tracking R package](https://epiforecasts.io/EpiNow2/)[@epinow2] and the documentation of our [R data package](https://epiforecasts.io/covidregionaldata/) [@covidregionaldata]. Interactive visualisations are powered by [`RtD3`](https://epiforecasts.io/RtD3/)[@rtd3]. Stored versions of our estimates can be found [here](https://dataverse.harvard.edu/dataverse/covid-rt) and the code used to generate them can be found [here](https://github.com/epiforecasts/covid-rt-estimates).**


**Note:** Our methodology remains an area of active research so please consider contacting us if interested in using, or evaluating, our approach. As an open-source project we also welcome code and methodology contributions, please see the linked code repositories for details on how to contribute.
